### ISSUE TITLE
No longer working in 1.14.3

### ISSUE THREAD

**Issue by Jay9519** [mathiasgit/CommandSpy#1]
[23:25:01] [Server thread/INFO]: Jay9519 issued server command: /commandspy
[23:25:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'commandspy' in plugin CommandSpy v2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-latest.jar:git-Spigot-595711b-c699792]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	at com.juno.commandspy.Main.onCommand(Main.java:79) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
	... 17 more

**Comment by mathiascode** [comment]
Wrong repository, should be posted here: https://github.com/kaboomserver/commandspy

I can't reproduce this issue. Tested the latest version of the plugin on a server running Paper 1.14.3. Did you make custom changes to the plugin?

**Comment by Jay9519** [comment]
sorry mate, I'll post over there.
I haven't made any changes but I am using Spigot 1.14.3, that could be why

**Comment by mathiascode** [comment]
No worries!
